/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.8.0
 * Product:       slf3x
 * Model-Version: 2.0.1
 */

#include "sensirion_common.h"
#include "sensirion_i2c.h"
#include "sensirion_i2c_hal.h"
#include "sensirion_test_setup.h"
#include "slf3x_i2c.h"
#include <inttypes.h>
#include <stdio.h>

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

TEST_GROUP (SLF3X_Tests) {
    void setup() {
        slf3x_init(0x08);
    }
};

TEST (SLF3X_Tests, test_stop_continuous_measurement1) {
    int16_t local_error = 0;

    local_error = slf3x_stop_continuous_measurement();
    CHECK_EQUAL_ZERO_TEXT(local_error, "stop_continuous_measurement");
}

TEST (SLF3X_Tests, test_read_product_identifier1) {
    int16_t local_error = 0;
    uint32_t product_identifier = 0;
    uint64_t serial_number = 0;

    local_error =
        slf3x_read_product_identifier(&product_identifier, &serial_number);
    CHECK_EQUAL_ZERO_TEXT(local_error, "read_product_identifier");
    printf("product_identifier: %u ", product_identifier);
    printf("serial_number: %" PRIx64 "\n", serial_number);
}

TEST (SLF3X_Tests, test_start_h2o_continuous_measurement1) {
    int16_t local_error = 0;
    int16_t raw_flow = 0;
    int16_t raw_temperature = 0;
    slf3x_signaling_flags_t signaling_flags = {.value = 0u};

    local_error = slf3x_start_h2o_continuous_measurement();
    CHECK_EQUAL_ZERO_TEXT(local_error, "start_h2o_continuous_measurement");
    local_error = slf3x_read_measurement_data_raw(&raw_flow, &raw_temperature,
                                                  &signaling_flags);
    CHECK_EQUAL_ZERO_TEXT(local_error, "read_measurement_data_raw");
    printf("raw_flow: %i ", raw_flow);
    printf("raw_temperature: %i ", raw_temperature);
    printf("signaling_flags: 0x%02x\n", signaling_flags.value);
    local_error = slf3x_stop_continuous_measurement();
    CHECK_EQUAL_ZERO_TEXT(local_error, "stop_continuous_measurement");
}

TEST (SLF3X_Tests, test_start_ipa_continuous_measurement1) {
    int16_t local_error = 0;
    int16_t raw_flow = 0;
    int16_t raw_temperature = 0;
    slf3x_signaling_flags_t signaling_flags = {.value = 0u};

    local_error = slf3x_start_ipa_continuous_measurement();
    CHECK_EQUAL_ZERO_TEXT(local_error, "start_ipa_continuous_measurement");
    local_error = slf3x_read_measurement_data_raw(&raw_flow, &raw_temperature,
                                                  &signaling_flags);
    CHECK_EQUAL_ZERO_TEXT(local_error, "read_measurement_data_raw");
    printf("raw_flow: %i ", raw_flow);
    printf("raw_temperature: %i ", raw_temperature);
    printf("signaling_flags: 0x%02x\n", signaling_flags.value);
    local_error = slf3x_stop_continuous_measurement();
    CHECK_EQUAL_ZERO_TEXT(local_error, "stop_continuous_measurement");
}

TEST (SLF3X_Tests, test_start_single_thermal_conductivity_measurement_async1) {
    int16_t local_error = 0;
    int16_t thermal_conductivity = 0;
    int16_t raw_temperature = 0;
    int16_t raw_delta_temperature = 0;

    local_error = slf3x_start_single_thermal_conductivity_measurement_async();
    CHECK_EQUAL_ZERO_TEXT(
        local_error, "start_single_thermal_conductivity_measurement_async");
    local_error = slf3x_read_thermal_conductivity_measurement_data(
        &thermal_conductivity, &raw_temperature, &raw_delta_temperature);
    CHECK_EQUAL_ZERO_TEXT(local_error,
                          "read_thermal_conductivity_measurement_data");
    printf("thermal_conductivity: %i ", thermal_conductivity);
    printf("raw_temperature: %i ", raw_temperature);
    printf("raw_delta_temperature: %i\n", raw_delta_temperature);
}

TEST (SLF3X_Tests, test_start_single_thermal_conductivity_measurement_sync1) {
    int16_t local_error = 0;
    int16_t thermal_conductivity = 0;
    int16_t raw_temperature = 0;
    int16_t raw_delta_temperature = 0;

    local_error = slf3x_start_single_thermal_conductivity_measurement_sync();
    CHECK_EQUAL_ZERO_TEXT(local_error,
                          "start_single_thermal_conductivity_measurement_sync");
    local_error = slf3x_read_thermal_conductivity_measurement_data(
        &thermal_conductivity, &raw_temperature, &raw_delta_temperature);
    CHECK_EQUAL_ZERO_TEXT(local_error,
                          "read_thermal_conductivity_measurement_data");
    printf("thermal_conductivity: %i ", thermal_conductivity);
    printf("raw_temperature: %i ", raw_temperature);
    printf("raw_delta_temperature: %i\n", raw_delta_temperature);
}
